# taplo TOML formatter configuration.

include = ["**/*.toml"]

[formatting]
align_entries = false
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true
column_width = 100
indent_string = "    "
reorder_keys = false
trailing_newline = true
